# Generated by Django 5.2.5 on 2026-04-17 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_created_at_user_is_active_user_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='failed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='success',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('reseller', 'Reseller'), ('user', 'User')], max_length=20),
        ),
    ]
