# Generated by Django 5.2.5 on 2026-04-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_created_at_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='nonwa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='rejected',
            field=models.IntegerField(default=0),
        ),
    ]
