# Generated by Django 5.2.5 on 2026-04-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_campaign_nonwa_campaign_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='nonwa',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='rejected',
        ),
    ]
