# Generated by Django 5.2.5 on 2026-04-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_created_at_alter_campaign_failed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='Active', max_length=10),
        ),
    ]
