# Generated by Django 5.2.5 on 2026-04-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='media',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='campaign',
            name='nonwa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='rejected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='results',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='failed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='success',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='total',
            field=models.IntegerField(),
        ),
    ]
