# Generated by Django 5.2.5 on 2026-04-23 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_campaign_media_campaign_nonwa_campaign_rejected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('credit', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('old_credit', models.IntegerField()),
                ('new_credit', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
